/*
* Copyright (c) 2017 Pedro Falcato
* This file is part of Onyx, and is released under the terms of the MIT License
* check LICENSE at the root directory for more information
*/
#ifndef _KERNEL_KEYS
#define _KERNEL_KEYS

enum
{
	KEYMAP_KEY_ESC = 0,
	KEYMAP_KEY_F1,
	KEYMAP_KEY_F2,
	KEYMAP_KEY_F3,
	KEYMAP_KEY_F4,
	KEYMAP_KEY_F5,
	KEYMAP_KEY_F6,
	KEYMAP_KEY_F7,
	KEYMAP_KEY_F8,
	KEYMAP_KEY_F9,
	KEYMAP_KEY_F10,
	KEYMAP_KEY_F11,
	KEYMAP_KEY_F12,
	KEYMAP_KEY_BRK,
	KEYMAP_KEY_PRTSC,	
	KEYMAP_KEY_INSERT,
	KEYMAP_KEY_HOME,
	KEYMAP_KEY_PGUP,
	KEYMAP_KEY_PGDN,
	KEYMAP_KEY_END,
	KEYMAP_KEY_KEYPAD_NUMLCK,
	KEYMAP_KEY_KEYPAD_SLASH,
	KEYMAP_KEY_KEYPAD_ASTERISK,
	KEYMAP_KEY_KEYPAD_DASH,
	KEYMAP_KEY_KEYPAD_7,
	KEYMAP_KEY_KEYPAD_8,
	KEYMAP_KEY_KEYPAD_9,
	KEYMAP_KEY_KEYPAD_4,
	KEYMAP_KEY_KEYPAD_5,
	KEYMAP_KEY_KEYPAD_6,
	KEYMAP_KEY_KEYPAD_1,
	KEYMAP_KEY_KEYPAD_2,
	KEYMAP_KEY_KEYPAD_3,
	KEYMAP_KEY_KEYPAD_PLUS,
	KEYMAP_KEY_KEYPAD_ENTER,
	KEYMAP_KEY_KEYPAD_0,
	KEYMAP_KEY_KEYPAD_DOT,
	KEYMAP_KEY_CAPS_LOCK,
	KEYMAP_KEY_ARROW_LEFT,
	KEYMAP_KEY_ARROW_RIGHT,
	KEYMAP_KEY_ARROW_UP,
	KEYMAP_KEY_ARROW_DOWN,
	KEYMAP_KEY_LSHIFT,
	KEYMAP_KEY_RSHIFT,
	KEYMAP_KEY_LCTRL,
	KEYMAP_KEY_FN,
	KEYMAP_KEY_WINKEY,
	KEYMAP_KEY_ALT,
	KEYMAP_KEY_ALTGR,
	KEYMAP_KEY_MENU,
	KEYMAP_KEY_RCTRL,
};

#endif