#!/bin/python3
import os
import sys

buildpkg_bin = os.environ.get("BUILDPKG_BIN")
sysroot = os.environ.get("SYSROOT")
os.environ["CC"] += " --sysroot=" + sysroot
os.environ["CXX"] += " --sysroot=" + sysroot

if buildpkg_bin == None:
	print("Error: Bad build environment")
	exit(1)

sys.argv[0] = buildpkg_bin

os.execv(buildpkg_bin, sys.argv)
