#!/bin/sh

# PKGDIR represents the directory where things will be put before they're completely
# compressed into a package
PKGDIR=$(mktemp -d)

# PKGSRC is the first argument and represents the place where the package actually is
PKGSRC=$1

NUM_THREADS=$(nproc)

MAKE="make -j${NUM_THREADS}"

TASK=$2

if [[ $TASK != "build" && $TASK != "package" && $TASK != "build+package" ]]; then
	echo "${0}: Error: No/invalid build task specified"
	rm -rf $PKGDIR
	exit 1
fi

# This system was totally not inspired by no one *cough cough Arch Linux cough cough*

. ${1}/PKGBUILD
if [[ $TASK == "build" || $TASK == "build+package" ]]; then
	pushd .
	cd $PKGSRC

	build
	popd
fi

if [[ $TASK == "build+package" || $TASK == "package" ]]; then
	pushd .
	cd $PKGSRC
	package

	popd

	tar -cf ${PKGNAME}-${PKGVER}.tar -C $PKGDIR .
	zstd -c -T0 --ultra -20 ${PKGNAME}-${PKGVER}.tar > ${PKGNAME}-${PKGVER}.tar.zst
	rm ${PKGNAME}-${PKGVER}.tar
fi

rm -rf $PKGDIR
