#!/bin/bash

# PKGDIR represents the directory where things will be put before they're completely
# compressed into a package
set -e

PKGDIR=$(mktemp -d)

trap 'rm -rf $PKGDIR' EXIT

TEMP=$(getopt -o 'o:' --long 'output-dir:,create-dir' -n 'buildpkg' -- "$@")

eval set -- "$TEMP"

OUTPUT_DIR='./'
create_dir=0

unset TEMP

while true; do
	echo $1
	case "$1" in
		'-o'|'--output-dir')
			echo "Using output dir '$2'"
			OUTPUT_DIR=$2
			shift 2
			continue
		;;
		'--create-dir')
			create_dir=1
			shift
			continue
		;;
		'--')
			shift
			break
		;;
	esac
done

OUTPUT_DIR=$(realpath "$OUTPUT_DIR")

# PKGSRC is the first argument and represents the place where the package actually is
PKGSRC=$1

NUM_THREADS=$(nproc)

MAKE="make -j${NUM_THREADS}"

TASK=$2

if [[ "$create_dir" = "1" ]]; then
	echo "Creating directory $OUTPUT_DIR"
	mkdir -p $OUTPUT_DIR
fi

if [[ $TASK != "build" && $TASK != "package" && $TASK != "build+package" ]]; then
	echo "${0}: Error: No/invalid build task specified"
	exit 1
fi

if [ -z "$STRIP" ]; then
echo "\$STRIP not specified, not stripping"
STRIP="true"
fi
# This system was totally not inspired by no one *cough cough Arch Linux cough cough*

cd "$1"

patch_package() {
	true
}

. PKGBUILD

if [ ! -f "${1}/PKGBUILD.stamp" ]; then
if [ -n "$fetch_cmd" ]; then
	sh -c "$fetch_cmd"
elif [ -n "$tarball" ]; then
	tarball_name="$(basename "$tarball")"

	wget "$tarball"
	tar xvf "$tarball_name"
	rm "$tarball_name"
fi
	pushd .
	patch_package
	popd
	touch "${1}/PKGBUILD.stamp"
fi

if [[ $TASK == "build" || $TASK == "build+package" ]]; then
	pushd .
	cd $PKGSRC

	build
	popd
fi

pushd $OUTPUT_DIR

if [[ $TASK == "build+package" || $TASK == "package" ]]; then
	pushd $PKGSRC
	package

	popd

	echo "Stripping binaries..."

	find "$PKGDIR/usr/bin" -type f -exec sh -c '(! echo {} | grep -q .*.o) && (file {} | grep -q ELF)' \; -exec $STRIP {} \; || true
	find "$PKGDIR/usr/libexec" -type f -exec sh -c '(! echo {} | grep -q .*.o) && (file {} | grep -q ELF)' \; -exec $STRIP {} \; || true
	find "$PKGDIR/usr/lib" -type f -exec sh -c '(! echo {} | grep -q .*.o) && (file {} | grep -q ELF)' \; -exec $STRIP {} \; || true
	echo "done."

	tar -cf ${PKGNAME}-${PKGVER}.tar -C $PKGDIR .
	zstd -c -T0 --ultra -13 ${PKGNAME}-${PKGVER}.tar > ${PKGNAME}-${PKGVER}.tar.zst
	rm ${PKGNAME}-${PKGVER}.tar
fi

popd
