#!/bin/sh

show_help()
{
        echo "Usage: geninitrd [options] shell scripts"
}

no_symlinks="false"
SHELL_SCRIPTS=""
COMPRESSION_METHOD=xz

while [ "$1" != "" ]; do
        case "$1" in
                --help|-h|-?)
                        show_help
                        exit 0
                        ;;
                --no-symlinks)
                        no_symlinks="true"
                        ;;
                --compression-method)
                        COMPRESSION_METHOD=$2
                        shift
                        ;;
		?*)
			SHELL_SCRIPTS="$SHELL_SCRIPTS $1 "
			;;
        esac
        shift
done

echo $SHELL_SCRIPTS

export DESTDIR=$(pwd)/initrd-root

echo "Target directory: $DESTDIR"

mkdir $DESTDIR

# Execute shell scripts
for script in $SHELL_SCRIPTS; do
	./$script
done

if [ $no_symlinks = "false" ]
then
        cd initrd-root
        ln -sf usr/lib .
        ln -sf usr/bin .
        cd ..
fi

echo "Creating a tarball"
# Tar it up
cd initrd-root

tar cvf initrd.tar *

mv initrd.tar ..
cd ..

rm -rf initrd-root

echo "Compressing it"
if [ "$COMPRESSION_METHOD" = "xz" ]
then
xz -5 -e -f initrd.tar
ARCHIVE_NAME="initrd.tar.xz"
elif [ "$COMPRESSION_METHOD" = "gz" ]
then
gzip -5 initrd.tar
ARCHIVE_NAME="initrd.tar.gz"
elif [ $COMPRESSION_METHOD = "bz" ]
then
bzip -5 initrd.tar
ARCHIVE_NAME="initrd.tar.bz2"
elif [ "$COMPRESSION_METHOD" = "none" ]; then
true
else
echo "Unknown compression method $COMPRESSION_METHOD"
exit 0
fi

