/* This file was automatically created by ./mksignames.
   Do not edit.  Edit support/mksignames.c instead. */

#include <signal.h>

/* A translation list so we can be polite to our users. */
const char *const signal_names[NSIG + 1] = {
    "EXIT",
    "HUP",
    "INT",
    "QUIT",
    "ILL",
    "TRAP",
    "ABRT",
    "BUS",
    "FPE",
    "KILL",
    "USR1",
    "SEGV",
    "USR2",
    "PIPE",
    "ALRM",
    "TERM",
    "16",
    "CHLD",
    "CONT",
    "STOP",
    "TSTP",
    "TTIN",
    "TTOU",
    "URG",
    "XCPU",
    "XFSZ",
    "VTALRM",
    "PROF",
    "WINCH",
    "IO",
    "PWR",
    "SYS",
    "32",
    "33",
    "RTMIN",
    "RTMIN+1",
    "RTMIN+2",
    "RTMIN+3",
    "RTMIN+4",
    "RTMIN+5",
    "RTMIN+6",
    "RTMIN+7",
    "RTMIN+8",
    "RTMIN+9",
    "RTMIN+10",
    "RTMIN+11",
    "RTMIN+12",
    "RTMIN+13",
    "RTMIN+14",
    "RTMIN+15",
    "RTMAX-14",
    "RTMAX-13",
    "RTMAX-12",
    "RTMAX-11",
    "RTMAX-10",
    "RTMAX-9",
    "RTMAX-8",
    "RTMAX-7",
    "RTMAX-6",
    "RTMAX-5",
    "RTMAX-4",
    "RTMAX-3",
    "RTMAX-2",
    "RTMAX-1",
    "RTMAX",
    (char *)0x0
};
